apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.name } }
  labels:
    app: { { .Values.app } }
spec:
  replicas: { { .Values.replicaCount } } # Specifies the number of pod replicas to run from the values.yaml file.
  selector:
    matchLabels:
      app: { { .Values.app } } # Ensures that the Deployment selects pods with this label.
  template:
    metadata:
      labels:
        app: { { .Values.app } } # The label assigned to each pod created by this deployment.
    spec:
      containers:
        - name: { { .Values.name } } # Name of the container.
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" # Container image, referencing the Helm values.yaml.
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.service.port } } # The port on which the container listens for requests.
