apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-service  # Name of the service for PostgreSQL.
  labels:
    app: {{ .Values.postgres.app }}  # Label to identify the service related to PostgreSQL.
spec:
  type: {{ .Values.postgres.service.type }}  # The service is only accessible within the cluster.
  ports:
  - port: {{ .Values.postgres.service.port }}  # Port exposed by the PostgreSQL container.
    targetPort: {{ .Values.postgres.service.targetPort }}  # The port on which the PostgreSQL container listens.
  selector:
    app: {{ .Values.postgres.app }}  # Pods with this label will be targeted by this service.
