apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.pvcName }}  # Name of the PVC, referenced from values.yaml.
  labels:
    app: postgres  # Label to identify the PVC related to PostgreSQL.
spec:
  accessModes:
    - ReadWriteOnce  # Defines that the volume can be mounted as read-write by a single node.
  resources:
    requests:
      storage: 1Gi
