apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: { { .Values.postgres.pvcName } } # Name of the PVC for PostgreSQL storage.
  labels:
    app: { { .Values.postgres.app } } # Label to identify the PVC related to PostgreSQL.
spec:
  accessModes:
    - ReadWriteOnce # The volume can be mounted as read-write by a single node.
  resources:
    requests:
      storage: { { .Values.postgres.storage.size } }
